### ISSUE TITLE
`.ploomber/stats` taking too much space when running 100+ notebooks simultaneously

### ISSUE THREAD

**Issue by avivajpeyi** [ploomber/ploomber-engine#83]
Im using ploomber-engine to analyze 100+ notebooks on a computing cluster. 

I hadnt realised that ploomber-engine creates a folder `.ploomber/stats`, and a `tmp_<blah>.txt` file for each notebook until I started running all the notebooks.

This resulted in a memory error (my `/home/user/` directory  where the `.ploomber-engine` folder is stored has a restriction of 10GB).

**Is it possible to customize the dir/path of these temp files?**

**Comment by avivajpeyi** [comment]
Ah, I see it in the docs https://docs.ploomber.io/en/latest/community/user-stats.html#how-to-opt-out

> As an open source project, we collect anonymous usage statistics to prioritize and find product gaps. This is optional and may be turned off either by:
> 
> Modify the configuration file ~/.ploomber/stats/config.yaml:
> 
> Change stats_enabled to false.
> 
> Set the environment variable:
> 
> export PLOOMBER_STATS_ENABLED=false

**Comment by edublancas** [comment]
thanks for reporting this, as you saw, you can turn off telemetry. but this sounds like a bug we need to investigate.

we added the `tmp_x.txt` files to check whether the filesystem is writable or not and the files should be deleted right after creation (also they're empty files so they shouldn't take much space).

did you hit a 10GB restriction? are the files being kept?

**Comment by avivajpeyi** [comment]
> did you hit a 10GB restriction? 

Yes, I hit the 10GB restriction limit: 

```
==> tess_atlas_catalog/log_pe/pe_37950002_368.log <==
OSError: [Errno 122] Disk quota exceeded: '/home/avajpeyi/.ploomber/stats/tmp_20QIYCP0JH.txt'

[00:05:20 - TESS-ATLAS] TOI 489 execution complete: False (4.81s)

==> tess_atlas_catalog/log_pe/pe_37950002_369.log <==
OSError: [Errno 122] Disk quota exceeded: '/home/avajpeyi/.ploomber/stats/tmp_XAAQ6KVZDH.txt'

[00:05:20 - TESS-ATLAS] TOI 490 execution complete: False (4.86s)

==> tess_atlas_catalog/log_pe/pe_37950002_36.log <==
OSError: [Errno 122] Disk quota exceeded: '/home/avajpeyi/.ploomber/stats/tmp_29XDY657HD.txt'

[00:05:29 - TESS-ATLAS] TOI 137 execution complete: False (10.94s)

==> tess_atlas_catalog/log_pe/pe_37950002_370.log <==
OSError: [Errno 122] Disk quota exceeded: '/home/avajpeyi/.ploomber/stats/tmp_G05959HT2P.txt'

```

Note that I already have used 6.4 GB so I think I just have ~4Gbs to work with. 


> are the files being kept?

The files aren't being kept, but since Im running 100s of notebooks in parallel I do hit the file limit just due to the existence of the temp files 😅  (the exact number is 3,672 notebooks in parallel).

**Comment by avivajpeyi** [comment]
Hmm ok this is a bit unfortunate, even with the above set to false (both the config and the env var), ploomber still tries to create these files.

I have also discovered that Im not hitting my mem limit but probably my `inode` limit

```
[00:00:06 - TESS-ATLAS] Preprocessing tess_atlas_catalog/toi_101.ipynb failed:
Traceback (most recent call last):
  File "/fred/oz200/avajpeyi/projects/tess-atlas/src/tess_atlas/notebook_controllers/notebook_executor.py", line 44, in execute_ipynb
    execute_notebook(
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.8/site-packages/ploomber_core/telemetry/telemetry.py", line 741, in wrapper
    self.log_api(**started)
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.8/site-packages/ploomber_core/telemetry/telemetry.py", line 506, in log_api
    (telemetry_enabled, uid, is_install) = _get_telemetry_info(
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.8/site-packages/ploomber_core/telemetry/telemetry.py", line 419, in _get_telemetry_info
    check_version(package_name, version)
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.8/site-packages/ploomber_core/telemetry/telemetry.py", line 370, in check_version
    settings = UserSettings()
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.8/site-packages/ploomber_core/config.py", line 20, in __init__
    self.writable = self._filesystem_writable()
  File "/fred/oz200/avajpeyi/envs/tess/lib/python3.8/site-packages/ploomber_core/config.py", line 155, in _filesystem_writable
    tmp.touch()
  File "/apps/sandybridge/software/Python/3.8.5-gni-2020.0/lib/python3.8/pathlib.py", line 1274, in touch
    fd = self._raw_open(flags, mode)
  File "/apps/sandybridge/software/Python/3.8.5-gni-2020.0/lib/python3.8/pathlib.py", line 1083, in _raw_open
    return self._accessor.open(self, flags, mode)
OSError: [Errno 122] Disk quota exceeded: '/home/avajpeyi/.ploomber/stats/tmp_X95NZD2YW1.txt'

[00:00:07 - TESS-ATLAS] TOI 101 execution complete: False (0.99s)
```
